name: Go Release
on: release
jobs:
  release:
    name: Release for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin, windows ]
        goarch: [ amd64, '386' ]
    steps:
    - uses: actions/checkout@master
    - name: Compile and release
      uses: ngs/go-release.action@97964071182a2e1eafd88226265517b9dd93fee9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}
